### ISSUE TITLE
Missing jdbcat-core repo

### ISSUE THREAD

**Issue by santiagobattaglino** [mobiletoly/jdbcat-ktor#1]
Hey! https://github.com/mobiletoly/jdbcat repo is no longer available?

**Comment by mobiletoly** [comment]
It will be back in a next few days. There were some important reasons why I had to take it down temporary :( I apologize for inconvenience.

**Comment by santiagobattaglino** [comment]
No problem, thanks for your reply! I'm using the jdbcat-core as a module for now.

**Comment by bengus** [comment]
@mobiletoly Many thanks for your simple, minimalistic example of working with this stack (Kotlin + Ktor + JDBCat + HikariCP + Koin + PostgreSQL + Testcontainers).
Any news about your core repo?)

**Comment by mobiletoly** [comment]
it is back:
https://github.com/mobiletoly/jdbcat-core
